version: '3.8'

networks:
  case_study_pf:
    name: case_study_pf
    driver: bridge

services:
  mysql_db:
    image: "mysql:latest"  # we have the same version of mysql in the prod
    container_name: mysql-container
    networks:
      - case_study_pf
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: analytics
      MYSQL_USER: nonroot
      MYSQL_PASSWORD: nonroot

  psql_db:
    image: "postgres:latest"
    container_name: psql-container
    networks:
      - case_study_pf
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./sql:/sql
    environment:
      POSTGRES_ROOT_USER: root
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  main:
    build:
      context: main
    networks:
      - case_study_pf
    environment:
      POSTGRESQL_CS: 'postgresql+psycopg2://postgres:password@psql_db:5432/main'
    depends_on:
      - psql_db
    command: ["python", "./main.py" ]

  # analytics:
  #   build:
  #     context: analytics
  #   networks:
  #     - case_study_pf
  #   environment:
  #     POSTGRESQL_CS: 'postgresql+psycopg2://postgres:password@psql_db:5432/main'
  #     MYSQL_CS: 'mysql+pymysql://nonroot:nonroot@mysql_db/analytics?charset=utf8'
  #   depends_on:
  #     - mysql_db
  #     - psql_db
  #     - main
  #   command: ["python", "./analytics.py" ]
